version: '3'
services: 
    web:
        environment: 
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        build:
            context: ./frontend/
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - ./frontend/:/app
    redis-server:
        image: 'redis'
    node-app:
        restart: on-failure
        build:
            context: ./backend/
            dockerfile: Dockerfile.node
        ports:
            - "8080:8080"
    tests:
        environment: 
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        build:
            context: ./frontend/
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./frontend/:/app
        command: ["npm", "run", "test"]